### ISSUE TITLE
Hee?

### ISSUE THREAD

**Issue by tjoen** [RdeLange/skill-dutchradio#1]
ziet er bekend uit..
Je had ook kunnen forken.

**Comment by RdeLange** [comment]
Hoi,

Yep, dat klopt. Kwam ik later achter. Ben inmiddels beter bekend met de github wereld, ik had eigenlijk geen idee toen hoe dat precies werkte.

Ik heb er al een tijd niet meer naar gekeken, maar volgens mij heb ik aan jouw basis een fuzzy functie toegevoegd zodat ik de betreffende zender niet exact hoefde uit te spreken.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by tjoen** [comment]
Ja, ik zag het. Handig....  :)
Had even een pull request gedaan. 

grtz. Theun
